export const skills = [
  "Acrobatics",
  "Acting",
  "Hearing",
  "Agriculture",
  "Monster Lore",
  "Local Lore",
  "Animal Lore",
  "Animal Handling",
  "Basket-weaving",
  "Astrology",
  "Astronomy",
  "Begging",
  "Blathering",
  "Brewing",
  "Bribery",
  "Carpentry",
  "Cartography",
  "Charm Person",
  "Charm Creature",
  "Clowning",
  "Joke telling",
  "Consume Alcohol",
  "Cook",
  "Cure Disease",
  "Dance",
  "Diagnose",
  "Disarm Trap",
  "Disguise",
  "Distract",
  "Divining",
  "Dowsing",
  "Dream Interpretation",
  "Drive Cart",
  "Convince",
  "Nature Lore",
  "Etiquette",
  "Evaluate",
  "Fire Eating",
  "Fishing",
  "Fleeing",
  "Yelling",
  "Crying",
  "Follow Trail",
  "Smelling",
  "Gem Cutting",
  "Haggle",
  "Heal Wounds",
  "Heraldry",
  "Herb Lore",
  "History",
  "Burying",
  "Identify Magical Artifact",
  "Digging",
  "Resist Disease",
  "Resist Fear",
  "Resist Poison",
  "Resist Magic",
  "Influence",
  "Intimidate",
  "Jest",
  "Juggle",
  "Sense Magic",
  "Magic Door",
  "Metallurgy",
  "Mining",
  "Palm Object",
  "Pick Lock",
  "Pick Pocket",
  "Prepare Poisons",
  "Public Speaking",
  "Read/Write",
  "Climbing",
  "Jumping",
  "Scapulomancy",
  "Scroll Use",
  "Secret Signs",
  "Seduction",
  "Set Trap",
  "Shadowing",
  "Stealth",
  "Hiding",
  "Lock Smashing",
  "Drawing",
  "Smithing",
  "Speak Additional Language",
  "Spot Trap",
  "Stewardship",
  "Stoneworking",
  "Story Telling",
  "Surgery",
  "Swim",
  "Tailor",
  "Tea Leaf Reading",
  "Theology",
  "Torture",
  "Transfix",
  "Undead Lore",
  "Ventriloquism",
  "Traveling",
  "Window Fishing",
  "Wrestling",
  "Acting Normal",
  "Alchemy",
  "Anatomy",
  "Antiques",
  "Armorer",
  "Bargain",
  "Barter",
  "Boating",
  "Bootlicking",
  "Lip Reading",
  "Bowyer",
  "Breath control",
  "Cribery",
  "Camouflage",
  "Camping",
  "Candlemaking",
  "Conceal item",
  "Fast-talk",
  "Construction",
  "Contortion",
  "Courtesan",
  "Scrounging",
  "Cultures",
  "Current events",
  "Deduction",
  "Explosives",
  "Detect lies",
  "Diplomacy",
  "Drug Lore",
  "Escape Arts",
  "Evaluate Item",
  "Falconry",
  "Farming",
  "Fine arts",
  "Marching",
  "Firebuilding",
  "First Aid",
  "Foraging",
  "Gadgetry",
  "Gambling",
  "Gesture",
  "Gunsmith",
  "Homeopathy",
  "Herbalism",
  "Herding",
  "Stalking",
  "Identify creature",
  "Improvisation",
  "Impersonation",
  "Interrogation",
  "Investigation",
  "Juggling",
  "Jumping",
  "Net",
  "Laundry",
  "Law Lore",
  "Leadership",
  "Leatherworking",
  "Legendary Lore",
  "Library use",
  "Boozing",
  "Listen",
  "Travel",
  "Literature",
  "Lockpicking",
  "Locksmith",
  "Deceive",
  "Manual labor",
  "Massage",
  "Masonry",
  "Mathematics",
  "Medicine Lore",
  "Mid-wife",
  "Mining",
  "Mountaineering",
  "Move Loudly",
  "Musical instrument",
  "Witch Lore",
  "Naturalist",
  "Navigation",
  "Negotiation",
  "Observation",
  "Occult lore",
  "Performance",
  "Persuasion",
  "Philosophy",
  "Podiatry",
  "Poetry",
  "Poison Lore",
  "Politics",
  "Pottery",
  "Prestidigitation",
  "Psychology",
  "Quick-draw",
  "Random theories",
  "Tarot Reading",
  "Recreational activities",
  "Religion",
  "Research",
  "Revolvers",
  "Riding",
  "Rope use",
  "Running",
  "Sabotage",
  "Safecracking",
  "Savoir-faire",
  "Sewing",
  "Cleaning",
  "Sculpting",
  "Sex appeal",
  "Sign language",
  "Singing",
  "Smuggling",
  "Spelunking",
  "Babble",
  "Storytelling",
  "Streetwise",
  "Survival",
  "Tactics",
  "Taxidermy",
  "Throwing",
  "Tightrope walking",
  "Torture",
  "Tracking",
  "Heal Wounds",
  "Detect Traps",
  "Trivia",
  "Urban legends",
  "Mimic Voice",
  "Weaponsmith",
  "Weaving",
  "Woodworking",
  "Speed Reading",
  "Spitting",
  "Dabbing",
  "Fashion",
  "Identify potion",
  "Study",
  "Irritate",
  "Burp Loudly",
  "Brew Coffee",
  "Chatter",
  "Snatching",
  "Painting",
  "Housekeeping",
  "Worship",
  "Preach",
  "Praying",
  "Mud-stepping",
  "Pleading",
  "Sense Weather",
  "Break Door",
  "Sense Spirits",
  "Tinker",
];
